version: "3"
services:
  dramatiq:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["bash", "/app/bin/run_dramatiq.sh"]
    depends_on:
      - redis
  periodiq:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["bash", "/app/bin/run_periodiq.sh"]
    depends_on:
      - dramatiq
  redis:
    command: redis-server --dbfilename 'redis.rdb'
    restart: unless-stopped
    image: redis:3-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/:/data
